# Generated by Django 5.2.1 on 2025-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
    ]
